on: [push]

jobs:
  sarif:
    runs-on: ubuntu-latest
    name: sarif multitool
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Sarif action step
        uses: ./ # Uses an action in the root directory
        with:
          command: 'help'
